spring:
  application:
    name: TgBot


  datasource:
   url: jdbc:postgresql://localhost:5435/mc_auth
   username: postgres
   password: postgres
   driver-class-name: org.postgresql.Driver


telegram:
  bot:
    username: SocialNetwork49Bot
    token: 7344453862:AAGI8I3lxFtmxF_6S5XGtV-VaBZvCtH1axI




