spring:
  application:
    name: TgBot

  data:
    redis:
      host: docker-redis-1
      port: 6379

telegram:
  bot:
    username: SocialNetwork49Bot
    token: 7344453862:AAGI8I3lxFtmxF_6S5XGtV-VaBZvCtH1axI

server:
  port: 8093
