spring:
  application:
    name: TgBot


#  datasource:
#   url: jdbc:postgresql://localhost:5435/mc_auth
#   username: postgres
#   password: postgres
#   driver-class-name: org.postgresql.Driver
token:
  signing:
    key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
    refreshTokenExpiration: 5m

telegram:
  bot:
    username: SocialNetwork49Bot
    token: 7344453862:AAGI8I3lxFtmxF_6S5XGtV-VaBZvCtH1axI




